#!/bin/bash
#Q1
if [[ $# -eq 1 ]]
then
    echo "great " 
else
     echo "error"
fi

#Q2
if [[ $# -eq 2 ]]
then 
     echo "great only 2"
else 
    echo "error"
fi

#Q3
if [[ $# -gt 1  ]] && [[ $# -lt 5 ]]
then 
     echo "great " 
else 
     echo "error"
fi

#Q4
if [[ $# -lt 10  ]]
then
    echo "you have entered the corccet argument"
else
    echo " false"
fi



